---

- hosts: all
  become: true
  vars:
      spark_version: 2.4.7
      hadoop_version: 2.7

  pre_tasks:
    - name: Remove swapfile from /etc/fstab
      mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      with_items:
        - swap
        - none
    - name: Disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

  roles:
    - role: adopt-openjdk
    - role: spark
